version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 655948565243.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build --platform linux/amd64 --tag 655948565243.dkr.ecr.us-east-1.amazonaws.com/lrc_server .
  post_build:
    commands:
      - docker push 655948565243.dkr.ecr.us-east-1.amazonaws.com/lrc:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "655948565243.dkr.ecr.us-east-1.amazonaws.com/lrc_server:latest" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
