version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  server:
    build: .
    container_name: lrc_server
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

  client:
    build: ./client
    container_name: lrc_client
    ports:
      - '4000:4000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

volumes:
  dbdata:
